DROP SCHEMA public CASCADE;
CREATE SCHEMA public;

CREATE TABLE countries(id SERIAL PRIMARY KEY, Name TEXT);
CREATE TABLE cities(id SERIAL PRIMARY KEY, Country_id INTEGER, Name TEXT);
CREATE TABLE citizens(id SERIAL PRIMARY KEY, City_id INTEGER, Name TEXT);